title: Scholar Options
extends@:
  type: default
  context: blueprints://pages

form:
  fields:
    tabs:
      type: tabs
      fields:
        options:
          type: tab
          fields:
            scholar_basic:
              type: section
              title: THEME_SCHOLAR.ADMIN.TITLES.BASIC
              underline: true
              data-fields@:
                [
                  '\Grav\Theme\Scholar::getConfigBlueprintFields',
                  "theme://blueprints/partials/basic.yaml",
                  "header.theme.",
                ]
        advanced:
          type: tab
          fields:
            scholar_advanced:
              type: section
              title: THEME_SCHOLAR.ADMIN.TITLES.ADVANCED
              underline: true
              data-fields@:
                [
                  '\Grav\Theme\Scholar::getConfigBlueprintFields',
                  "theme://blueprints/partials/advanced.yaml",
                  "header.theme.",
                ]
            scholar_expert:
              type: section
              title: THEME_SCHOLAR.ADMIN.TITLES.EXPERT
              underline: true
              data-fields@:
                [
                  '\Grav\Theme\Scholar::getConfigBlueprintFields',
                  "theme://blueprints/partials/expert.yaml",
                  "header.theme.",
                ]
